# Generated by Django 4.2.6 on 2023-10-30 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('hour', models.IntegerField(validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)], verbose_name='hour')),
                ('minute', models.IntegerField(validators=[django.core.validators.MaxValueValidator(59), django.core.validators.MinValueValidator(0)], verbose_name='minute')),
                ('speed', models.FloatField(verbose_name='speed')),
                ('direction', models.IntegerField(validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(0)], verbose_name='angle')),
                ('department', models.CharField(max_length=100, verbose_name='department')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('region', models.CharField(max_length=100, verbose_name='region')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
            ],
            options={
                'verbose_name': 'wind',
                'verbose_name_plural': 'winds',
                'ordering': ['date'],
            },
        ),
    ]
